language: php

matrix:
  include:
    - php: 7.1
      env: PHPUNIT_TEST=1
    - php: 7.2
      env: PHPUNIT_COVERAGE_TEST=1
    - php: 7.1
      env: PHPCS_TEST=1
    - php: 7.3
      env: PHPUNIT_TEST=1
    - php: 7.4
      env: PHPUNIT_TEST=1
    - php: 7.4
      env: PHPSTAN_TEST=1
    - php: 7.4
      env: LINT_CHECK=1
    - php: 7.4
      env: PSALM_TEST=1
    - php: 7.4
      env: DUPLICATE_CODE_CHECK=1

before_script:
  - composer validate
  - if [[ $DUPLICATE_CODE_CHECK ]]; then sudo apt remove -y nodejs && curl -sL https://deb.nodesource.com/setup_14.x -o nodesource_setup.sh && sudo bash nodesource_setup.sh && sudo apt install -y build-essential nodejs && which npm && npm install jscpd@3.2.1  ;fi

install:
  - composer global require hirak/prestissimo
  - composer install --prefer-dist

script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit -d memory_limit=4G  tests/; fi
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then phpdbg -qrr vendor/bin/phpunit -d memory_limit=4G --coverage-clover=coverage.xml   tests/   ; fi
  - if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs --standard=ruleset.xml --extensions=php --tab-width=4 -sp src tests ; fi
  - if [[ $PHPSTAN_TEST ]]; then vendor/bin/phpstan analyse --level=6 -c tests/phpstan.neon src/; fi
  - if [[ $LINT_CHECK ]]; then vendor/bin/parallel-lint src/ tests/; fi
  - if [[ $DUPLICATE_CODE_CHECK ]]; then node_modules/jscpd/bin/jscpd src && node_modules/jscpd/bin/jscpd tests ; fi
  - if [[ PSALM_TEST ]]; then vendor/bin/psalm --show-info=true; fi

after_script:
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml; fi
